### ISSUE TITLE
Lint unused puppet modules and/or other files

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ckan-puppet-centos#4]
Looks like possibly `memcached`, `puppi` and possibly `monitor` aren't actually invoked.

**Comment by BobTorgerson** [comment]
I agree, and these are leftover from my work of incorporating other people's modules into ours. We can safely remove those puppet modules.

**Comment by brucecrevensten** [comment]
Probably should remove `puppet/modules/ckan/templates/custom.erb`

**Comment by brucecrevensten** [comment]
Also should run through this list and see if we don't need some of these packages:

```
  $ckan_libs = ['libcurl-devel','httpd', 'xml-common', 'git', 'libxslt', 'libxslt-devel',
                'libxml2', 'libxml2-devel', 'gcc', 'gcc-c++', 'make', 'supervisor',
                'java-1.7.0-openjdk-devel', 'java-1.7.0-openjdk', 'tomcat6', 'xalan-j2', 'unzip',
                'policycoreutils-python','mod_wsgi','xml-commons-resolver','xml-commons-apis']
```

**Comment by BobTorgerson** [comment]
I've updated the number of modules that are required to be installed by the "shell" provisioning portion of the Vagrantfile. This can be closed.
