### ISSUE TITLE
Configure CKAN to be served via wsgi module

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ckan-puppet-centos#6]
The initial build I was tracking didn't actually wrap in the `wsgi` configuration.  I followed (these directions)[http://docs.ckan.org/en/ckan-2.2/deployment.html] but left `nginx` out of the loop, and it appeared to connect OK though I kept getting various errors in the `/var/log/httpd/ckan.error.log`.

**Comment by BobTorgerson** [comment]
This is working correctly. By looping in that missing WSGI script, the Apache configuration is finding the proper environment it requires and starting the CKAN virtual environment.
