### ISSUE TITLE
Harmonize configuration file

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ckan-puppet-centos#7]
The `production.ini` templates in the source puppet module we're working from seemed to span a few generations of CKAN, and while it looked almost correct, we should ensure that it has what we want.

Also need to manually edit the `config.pp` file to inject a valid [beaker secret](http://pylons-webframework.readthedocs.org/en/latest/sessions.html) (looks like it can be any string), as well as our application's (uuid)[https://www.uuidgenerator.net/].  This needs to be done prior to running `vagrant up`.

**Comment by BobTorgerson** [comment]
I believe that I have "harmonized" the configuration file to allow for the CKAN service to run without errors related to a misconfiguration. It is still failing due to Solr not being available, but that is a different issue.

**Comment by brucecrevensten** [comment]
you sure that all the configs for 2.2 are present?  (I think they were darn close.  I generated a new one with Paster and did a vimdiff, and while the one in the repo isn't _quite_ the same they're quite similar).  maybe worth a re-check later.

**Comment by BobTorgerson** [comment]
I suppose I can't say for certain that all of the configurations are correct, but reading through the documentation on new fields, the old fields do not interfere with the new fields when they would have conflicted from a previous CKAN version. One such field is under the comment "# Storage", which has the old way of dealing with a storage directory defined along with the new way. 

I will investigate further.
