### ISSUE TITLE
Enable VM to be reachable from host

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ckan-puppet-centos#8]
It seems like `iptables` isn't quite configured correctly to allow us to connect to the guest resources via the host through Vagrant's port forwarding.  Disabling `iptables` works but needs to be configured correctly during provisioning to allow (at least) access to the various things we'll use for development:
- connect to CKAN itself! (80)
- connect to the harvester (???)
- connect to Solr admin panel (8080)

**Comment by BobTorgerson** [comment]
I have modified the firewall to accept connections on port 80 and port 8080 on the VM. Looking into what is needed for the CKAN harvester.

**Comment by BobTorgerson** [comment]
It looks like the CKAN harvester is capable of being run without any additional ports being open. We should be good with just having port 80 and port 8080 open on the development VMs.
